---
- name: Install Apache on Development Server
  hosts: host1 
  gather_facts: true
  tasks:
    - name: Install Apache
      when: ansible_distribution == "CentOS"
      yum:
        name: httpd
        state: latest
      register: install_apache_result
    
    - name: Copy Application files
      copy:
        src: ../app/index.html
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: '0644'
      register: index_html
    
    - name: Start and Enable Apache
      when: 
       
        - ansible_service_mgr == "systemd"
        - index_html is changed
      systemd: 
        state: restarted
        name: httpd
        enabled: yes 

    
